import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <div className="flex flex-col justify-between h-screen">{children}</div>
      </body>
    </html>
  );
}
